### ISSUE TITLE
The delete button wipes all entries not the just the last token

### ISSUE THREAD

**Issue by zackzachariah** [ichthala/goldengrove#7]
When composing a poem

**Comment by zack** [comment]
Go big or go home.

**Comment by zack** [comment]
:-1:

**Comment by zackzachariah** [comment]
Then you shouldn't have both a delete & a clear button!

**Comment by zackzachariah** [comment]
And i'm still mad you got @zack <shake fist>

**Comment by zack** [comment]
I just asked.

![](https://i.imgur.com/VgRUMu2.gif)

**Comment by ichthala** [comment]
Good catch!

**Comment by ichthala** [comment]
Um, I mean, STOP COMPLAINING AND ISSUE A PULL REQUEST

**Comment by zackzachariah** [comment]
I DON"T KNOW RUBY SRY USE A REAL LANGUAGE AND I WOULD

**Comment by ichthala** [comment]
I'll do it I'll do it -_-
